version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in install phase.
  pre_build:
    commands:
      - composer install --no-interaction
  build:
    commands:
      - echo Nothing to do in build phase.
  post_build:
    commands:
      - echo Nothing to do in post_build phase.
artifacts:
  base-directory: src
  files:
    - **/*
