version: 0.1

environment_variables:
  plaintext:
    COMPOSER_ALLOW_SUPERUSER: "true"

phases:
  install:
    commands:
      - echo Nothing to do in install phase.
  pre_build:
    commands:
      - cd src && composer install --no-interaction
  build:
    commands:
      - echo Nothing to do in build phase.
  post_build:
    commands:
      - echo Nothing to do in post_build phase.
artifacts:
  base-directory: src
  files:
    - "**/*"
